sonar.projectKey=diegopeixoto_unicornstudio-react
sonar.organization=diegopeixoto

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
